### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by dotarjun** [potamides/dotfiles#1]
This is pretty cool but will it work on Zorin OS16? I just got into linux and started going down the  "ricing" rabbithole.

**Comment by potamides** [comment]
I don't now for sure, since I've never used Zorin OS but I'm pretty sure that some things won't work without issues out of the box. Some stuff in my rice is Arch Linux specific, like the package installation script, so that won't work. Other stuff might work, but depending on the version of the packages in the Zorin repos and probably other idiosyncrasies of that OS I don't now of, some things might break.

With that in mind, I think the answer depends on your goal. Are there some bits and pieces here that interest you that you would like to incorporate into your own rice? Then yes, it will probably work on Zorin and if not, there is a good chance that the problems are easy to fix. Do you want to use this rice as a whole and/or black box? Then the answer is probably no.

Since you are new to ricing, I encourage you to do the former. If you pick only the components you are interested in and check them thoroughly before use, you will avoid unpleasant surprises and get a system tailored to your own preferences which, in my opinion, is the essence of ricing.

**Comment by dotarjun** [comment]
tysm
